# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e721ce434f317ed3e1a86f3fdadf5268fa7dc0689d0489c3f67344ef646a325d5404817398b328691d8831e701f9467b104217828d7f9afefe166dd7852e08c

test:
  secret_key_base: af93ea036420339e8ce8f8c6a936594df4bc82d69c727e472059b0fe3b41ee339f3332c083c3bd1bf3b58254c98f7ee682f96968657404b6411da62e3a95d3a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
